src/objects/Convert_Attachments_to_Files_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls when and how certain attachments are converted to files.</description>
    <fields>
        <fullName>Convert_in_Near_Real_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables &apos;after insert&apos; trigger on Attachment that enqueues job to convert into Files in near real-time. This async conversion does not slow down save transaction, and if &apos;Delete Attachments&apos; option is enabled then deletes in separate transaction too.</description>
        <inlineHelpText>Enables &apos;after insert&apos; trigger on Attachment that enqueues job to convert into Files in near real-time. This async conversion does not slow down save transaction, and if &apos;Delete Attachments&apos; option is enabled then deletes in separate transaction too.</inlineHelpText>
        <label>Convert in Near Real Time?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delete_Attachment_Once_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked then conversion process will delete the original Attachment once successfully converted to File. You may want to delete them to save storage space in your org.</description>
        <inlineHelpText>When checked then conversion process will delete the original Attachment once successfully converted to File. You may want to delete them to save storage space in your org.</inlineHelpText>
        <label>Delete Attachment Once Converted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_Private_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Attachments have &apos;IsPrivate&apos; field that limits access to owner and admins. Files related to records are not private. Enable this option to share converted private attachment Files with their parent record and to anyone who has access to the parent record.</description>
        <inlineHelpText>Attachments have &apos;IsPrivate&apos; field that limits access to owner and admins. Files related to records are not private. Enable this option to share converted private attachment Files with their parent record and to anyone who has access to the parent record.</inlineHelpText>
        <label>Share Private Attachments?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_Type__c</fullName>
        <defaultValue>&quot;V&quot;</defaultValue>
        <description>The ContentDocumentLink.ShareType value to use for converted files.
V = view only
I = inferred by user&apos;s editability of related record
C = collaborator, view/edit (not supported if related to standard objects)</description>
        <inlineHelpText>The ContentDocumentLink.ShareType value to use for converted files.
V = view only
I = inferred by user&apos;s editability of related record
C = collaborator, view/edit (not supported if related to standard objects)</inlineHelpText>
        <label>Share Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <defaultValue>&quot;InternalUsers&quot;</defaultValue>
        <description>The ContentDocumentLink.Visibility value to use for converted files. For any user with permission to view the file, this further controls which set of users can actually see it.
&quot;InternalUsers&quot; = only internal users with permission to view file (available if communities enabled)
&quot;AllUsers&quot; = all users, including community users, with permission to view file</description>
        <inlineHelpText>The ContentDocumentLink.Visibility value to use for converted files.
&quot;InternalUsers&quot; = only internal users with permission to view file (available if communities enabled)
&quot;AllUsers&quot; = all users, including community users, with permission to view file</inlineHelpText>
        <label>Visibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Convert Attachments to Files Settings</label>
</CustomObject>

src/classes/ConvertAttachmentsSettingsControllerTest.cls
/**
 * Developed by Doug Ayers (douglascayers.com)
 */
@isTest
private class ConvertAttachmentsSettingsControllerTest {

    @isTest
    static void test_communities_enabled() {

        Test.startTest();

        ConvertAttachmentsSettingsController controller = new ConvertAttachmentsSettingsController();

        Boolean isCommunitiesEnabled = controller.isCommunitiesEnabled;

        Test.stopTest();

        System.assertEquals( Schema.getGlobalDescribe().containsKey( 'Network' ), isCommunitiesEnabled );

    }

    @isTest
    static void test_save_new_settings() {

        Convert_Attachments_to_Files_Settings__c settings = Convert_Attachments_to_Files_Settings__c.getOrgDefaults();
        settings.Share_Type__c = 'I';
        settings.Visibility__c = 'AllUsers';
        settings.Convert_in_Near_Real_Time__c = false;
        settings.Delete_Attachment_Once_Converted__c = true;
        settings.Convert_Private_Attachments__c = true;
        settings.Share_Private_Attachments__c = true;

        Test.startTest();

        ConvertAttachmentsSettingsController controller = new ConvertAttachmentsSettingsController();

        controller.settings = settings;
        controller.convertAndSharePrivateAttachments = 'yes_convert_yes_share';

        controller.save();

        Test.stopTest();

        System.assertEquals( true, controller.success );
        System.assert( controller.message.containsIgnoreCase( 'Settings saved successfully' ) );

    }

    @isTest
    static void test_update_existing_settings() {

        Convert_Attachments_to_Files_Settings__c settings = Convert_Attachments_to_Files_Settings__c.getOrgDefaults();
        settings.Share_Type__c = 'I';
        settings.Visibility__c = 'AllUsers';
        settings.Convert_in_Near_Real_Time__c = false;
        settings.Delete_Attachment_Once_Converted__c = true;
        settings.Convert_Private_Attachments__c = true;
        settings.Share_Private_Attachments__c = true;

        upsert settings;

        Test.startTest();

        ConvertAttachmentsSettingsController controller = new ConvertAttachmentsSettingsController();

        controller.settings = settings;

        controller.save();

        Test.stopTest();

        System.assertEquals( true, controller.success );
        System.assert( controller.message.containsIgnoreCase( 'Settings saved successfully' ) );

    }

    @isTest
    static void test_save_error() {

        Convert_Attachments_to_Files_Settings__c settings = Convert_Attachments_to_Files_Settings__c.getOrgDefaults();
        settings.Share_Type__c = 'I';
        settings.Visibility__c = 'AllUsers';
        settings.Convert_in_Near_Real_Time__c = false;
        settings.Delete_Attachment_Once_Converted__c = true;
        settings.Convert_Private_Attachments__c = true;
        settings.Share_Private_Attachments__c = true;

        upsert settings;

        Test.startTest();

        ConvertAttachmentsSettingsController controller = new ConvertAttachmentsSettingsController();

        controller.settings = settings;

        // leave fields blank, cause validation errors
        controller.settings.visibility__c = null;

        controller.save();

        System.assertEquals( false, controller.success );
        System.assert( controller.message.containsIgnoreCase( 'Please answer all questions' ) );

        // fix validation error
        controller.settings.visibility__c = 'AllUsers';

        delete settings; // will cause exception on save because ID field is still populated on controller's reference

        controller.save();

        Test.stopTest();

        System.assertEquals( false, controller.success );

    }

    @isTest
    static void test_inferConvertAndSharePrivateAttachments() {

        Test.startTest();

        ConvertAttachmentsSettingsController controller = new ConvertAttachmentsSettingsController();

        String yes_convert_yes_share = controller.inferConvertAndSharePrivateAttachments( new Convert_Attachments_to_Files_Settings__c(
            Convert_Private_Attachments__c = true,
            Share_Private_Attachments__c = true
        ));

        String yes_convert_no_share = controller.inferConvertAndSharePrivateAttachments( new Convert_Attachments_to_Files_Settings__c(
            Convert_Private_Attachments__c = true,
            Share_Private_Attachments__c = false
        ));

        String no_convert_no_share = controller.inferConvertAndSharePrivateAttachments( new Convert_Attachments_to_Files_Settings__c(
            Convert_Private_Attachments__c = false,
            Share_Private_Attachments__c = false
        ));

        Test.stopTest();

        System.assertEquals( 'yes_convert_yes_share', yes_convert_yes_share );
        System.assertEquals( 'yes_convert_no_share', yes_convert_no_share );
        System.assertEquals( 'no_convert_no_share', no_convert_no_share );

    }

    @isTest
    static void test_applyConvertAndSharePrivateAttachments() {

        Test.startTest();

        ConvertAttachmentsSettingsController controller = new ConvertAttachmentsSettingsController();

        Convert_Attachments_to_Files_Settings__c yes_convert_yes_share = new Convert_Attachments_to_Files_Settings__c();
        controller.applyConvertAndSharePrivateAttachments( yes_convert_yes_share, 'yes_convert_yes_share' );

        Convert_Attachments_to_Files_Settings__c yes_convert_no_share = new Convert_Attachments_to_Files_Settings__c();
        controller.applyConvertAndSharePrivateAttachments( yes_convert_no_share, 'yes_convert_no_share' );

        Convert_Attachments_to_Files_Settings__c no_convert_no_share = new Convert_Attachments_to_Files_Settings__c();
        controller.applyConvertAndSharePrivateAttachments( no_convert_no_share, 'no_convert_no_share' );

        Test.stopTest();

        System.assertEquals( true, yes_convert_yes_share.Convert_Private_Attachments__c );
        System.assertEquals( true, yes_convert_yes_share.Share_Private_Attachments__c );

        System.assertEquals( true, yes_convert_no_share.Convert_Private_Attachments__c );
        System.assertEquals( false, yes_convert_no_share.Share_Private_Attachments__c );

        System.assertEquals( false, no_convert_no_share.Convert_Private_Attachments__c );
        System.assertEquals( false, no_convert_no_share.Share_Private_Attachments__c );

    }

}