src/objects/Convert_Attachments_to_Files_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls when and how certain attachments are converted to files.</description>
    <fields>
        <fullName>Convert_in_Near_Real_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables &apos;after insert&apos; trigger on Attachment that enqueues job to convert into Files in near real-time. This async conversion does not slow down save transaction, and if &apos;Delete Attachments&apos; option is enabled then deletes in separate transaction too.</description>
        <inlineHelpText>Enables &apos;after insert&apos; trigger on Attachment that enqueues job to convert into Files in near real-time. This async conversion does not slow down save transaction, and if &apos;Delete Attachments&apos; option is enabled then deletes in separate transaction too.</inlineHelpText>
        <label>Convert in Near Real Time?</label>
        <type>Checkbox</type>
    </fields>
    <label>Convert Attachments to Files Settings</label>
</CustomObject>

src/classes/ConvertAttachmentsScheduleController.cls
public with sharing class ConvertAttachmentsScheduleController {

    public ScheduleRequest request { get; set; }

    public Boolean enableTrigger { get; set; }

    public String message { get; set; }

    public Boolean success { get; set; }

    public ConvertAttachmentsScheduleController() {
        this.request = new ScheduleRequest();
        this.enableTrigger = Convert_Attachments_to_Files_Settings__c.getInstance().Convert_in_Near_Real_Time__c;
    }

    public void save() {



    }

    public class ScheduleRequest {

        public Boolean sunday { get; set; }
        public Boolean monday { get; set; }
        public Boolean tuesday { get; set; }
        public Boolean wednesday { get; set; }
        public Boolean thursday { get; set; }
        public Boolean friday { get; set; }
        public Boolean saturday { get; set; }

        public Integer timeOfDay { get; set; } // 0-23 military time

        public ScheduleRequest() {
            this.timeOfDay = 0;
        }

    }

}