src/objects/Convert_Attachments_to_Files_Log__c.object
<CustomObject>
    <description>When deployed as a managed package then users cannot see errors logged to the Debug Log. This object stores any errors and messages the Adminsitrator may need to know about when troubleshooting conversion issues. You may delete these records after you have reviewed them.</description>
    <label>Convert Attachments to Files Log</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Convert Attachments to Files Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Convert_Attachments_to_Files_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls when and how certain attachments are converted to files.</description>
    <fields>
        <fullName>Convert_in_Near_Real_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables &apos;after insert&apos; trigger on Attachment that enqueues job to convert into Files in near real-time. This async conversion does not slow down save transaction, and if &apos;Delete Attachments&apos; option is enabled then deletes in separate transaction too.</description>
        <inlineHelpText>Enables &apos;after insert&apos; trigger on Attachment that enqueues job to convert into Files in near real-time. This async conversion does not slow down save transaction, and if &apos;Delete Attachments&apos; option is enabled then deletes in separate transaction too.</inlineHelpText>
        <label>Convert in Near Real Time?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delete_Attachment_Once_Converted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked then conversion process will delete the original Attachment once successfully converted to File. You may want to delete them to save storage space in your org.</description>
        <inlineHelpText>When checked then conversion process will delete the original Attachment once successfully converted to File. You may want to delete them to save storage space in your org.</inlineHelpText>
        <label>Delete Attachment Once Converted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_Private_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Attachments have &apos;IsPrivate&apos; field that limits access to owner and admins. Files related to records are not private. Enable this option to share converted private attachment Files with their parent record and to anyone who has access to the parent record.</description>
        <inlineHelpText>Attachments have &apos;IsPrivate&apos; field that limits access to owner and admins. Files related to records are not private. Enable this option to share converted private attachment Files with their parent record and to anyone who has access to the parent record.</inlineHelpText>
        <label>Share Private Attachments?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Share_Type__c</fullName>
        <defaultValue>&quot;V&quot;</defaultValue>
        <description>The ContentDocumentLink.ShareType value to use for converted files.
V = view only
I = inferred by user&apos;s editability of related record
C = collaborator, view/edit (not supported if related to standard objects)</description>
        <inlineHelpText>The ContentDocumentLink.ShareType value to use for converted files.
V = view only
I = inferred by user&apos;s editability of related record
C = collaborator, view/edit (not supported if related to standard objects)</inlineHelpText>
        <label>Share Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <defaultValue>&quot;InternalUsers&quot;</defaultValue>
        <description>The ContentDocumentLink.Visibility value to use for converted files. For any user with permission to view the file, this further controls which set of users can actually see it.
&quot;InternalUsers&quot; = only internal users with permission to view file (available if communities enabled)
&quot;AllUsers&quot; = all users, including community users, with permission to view file</description>
        <inlineHelpText>The ContentDocumentLink.Visibility value to use for converted files.
&quot;InternalUsers&quot; = only internal users with permission to view file (available if communities enabled)
&quot;AllUsers&quot; = all users, including community users, with permission to view file</inlineHelpText>
        <label>Visibility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Convert Attachments to Files Settings</label>
</CustomObject>

src/classes/ConvertAttachmentsToFilesScheduleTest.cls
/**
 * Developed by Doug Ayers (douglascayers.com)
 */
@isTest
private class ConvertAttachmentsToFilesScheduleTest {

    @isTest
    static void test_schedulable() {

        Convert_Attachments_to_Files_Settings__c settings = Convert_Attachments_to_Files_Settings__c.getOrgDefaults();
        settings.Share_Type__c = 'I';
        settings.Visibility__c = 'AllUsers';
        settings.Convert_in_Near_Real_Time__c = false;
        settings.Delete_Attachment_Once_Converted__c = true;
        settings.Share_Private_Attachments__c = true;

        upsert settings;

        Test.startTest();

        System.schedule( 'Conversion Job', '0 0 13 * * ?', new ConvertAttachmentsToFilesSchedulable() );

        Test.stopTest();

        System.assertEquals( 0, [ SELECT count() FROM Convert_Attachments_to_Files_Log__c ] );

    }

    @isTest
    static void test_errors() {

        ConvertAttachmentsToFilesSchedulable job = new ConvertAttachmentsToFilesSchedulable();

        job.batchSize = null; // will cause error

        Test.startTest();

        System.schedule( 'Conversion Job', '0 0 13 * * ?', job );

        Test.stopTest();

        System.assertEquals( 1, [ SELECT count() FROM Convert_Attachments_to_Files_Log__c ] );

    }

}